# to build image:
# > docker-compose build

# to run container (and keep atached to the container)
# > docker-compose up [<service_name>]

# to run container as a daemon
# > docker-compose up -d [<service_name>]
# to attach to daemon container
# > docker exec -it <container_id> bash

# to stop the started container
# > docker-compose stop [<service_name>]

# to stop and remove the started container
# > docker-compose down [<service_name>]

version: "3"
services:
  futfem-front:
    image: futfem-front
    container_name: futfem-front
    restart: always
    tty: true
    build:
      context: .
      dockerfile: ./futfem-front.Dockerfile
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/site.conf
        - ./dist/tikitakas:/etc/nginx/nginx/html
    ports:
        - 8081:80
    networks:
      - futfem-network
networks:
  futfem-network:
    driver: bridge