version: "3"

services:
  futfem-front:
    image: futfem-front
    container_name: futfem-front
    restart: always
    build:
      context: .
      dockerfile: ./futfem-front.Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '127.0.0.1:4000:80'
    networks:
      - futfem-net

networks:
  futfem-net:

  
  